version: "3.1"

services:

  nginx:
    image: nginx:1.15
    volumes:
      - ./z-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./z-nginx/site:/usr/share/nginx/html
      - ./z-nginx/my-site.com.crt:/etc/nginx/my-site.com.crt
      - ./z-nginx/my-site.com.key:/etc/nginx/my-site.com.key

    ports:
      - 443:443

    depends_on:
      - joget

  joget:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - postgres

    volumes:
      - ./z-joget/app_datasource.properties:/opt/joget/wflow/app_datasource.properties
      - ./z-joget/app_datasource-postgresql.properties:/opt/joget/wflow/app_datasource-postgresql.properties
      - ./z-joget/postgresql-42.2.1.jar:/opt/joget/apache-tomcat-8.5.41/lib/postgresql.jar
      - ./z-tomcat/server.xml:/opt/joget/apache-tomcat-8.5.41/conf/server.xml
      - ./z-tomcat/ssl.keystore:/ssl.keystore
      - ./z-tomcat/ssl.truststore:/ssl.truststore
      - ./logs/tomcat:/opt/joget/apache-tomcat-8.5.41/logs

  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ./z-postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - v-postgres-data:/var/lib/postgresql/data

volumes:
  v-postgres-data: